# Generated by Django 5.2.8 on 2025-11-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobooking',
            name='zoo_booking_date_arrive',
            field=models.DateField(blank=True, null=True),
        ),
    ]
